export const REQUEST_POSTS = 'REQUEST_POSTS';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const RESET_POST ='RESET_POST';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const RESET_COMMENTS = 'RESET_COMMENTS';
